### ISSUE TITLE
git to heroku is hanging!

### ISSUE THREAD

**Issue by prashm** [ddollar/heroku-accounts#13]
Hi,

There is no problem when I do:
$ git push origin master
Everything up-to-date

But it hangs when i try to remote to hero repo:
$ git push heroku master
ssh: connect to host heroku.com port 22: Bad file number
fatal: The remote end hung up unexpectedly

I'm using windows7 64 bit but I don't think that should make any difference. I'm behind firewall but then if that was the problem my attempt in connecting to github should have failed too. So I don't think that is the problem. I've googled this extensively but could not get an answer.

Can someone please help me with this? I'm unable to deploy my ruby app to heroku because of this.

**Comment by grosser** [comment]
`heroku git:remote -a <name>` fixes it
