### ISSUE TITLE
Bad owner or permissions on /Users/username/.ssh/config

### ISSUE THREAD

**Issue by matthewswallace** [ddollar/heroku-accounts#15]
This is a great plugin till I got to the point of pushing to heroku.

I installed the plugin as per the instructions in the README file created two accounts one called personal and one called dlab. I tested my personal account with an app that I already had working and all seems to work as expected. 

I created a new rails app added git switched to dlab user and then ran  $> heroku create myapp. Creating the app worked fine so I grabbed the heroku git address that was created and did git remote add heroku "<git address>" Then when I did git push heroku master I got the following message "Bad owner or permissions on /Users/username/.ssh/config" message.

**Comment by vikasjiitk** [comment]
600 didn't worked for me but 6000 worked -_-

**Comment by vb078** [comment]
Thank you

**Comment by Cerealkillerway** [comment]
Worked, thanks for the tip

**Comment by finethanks** [comment]
Thanks!

**Comment by dajnz** [comment]
Thank you!

**Comment by dhanabalt** [comment]
Thank you

**Comment by zxybazh** [comment]
Great, chmod 600 works !

**Comment by uuoofan** [comment]
Thanks!

**Comment by camilo-globant** [comment]
Thanks! 600 works!

**Comment by wkblack** [comment]
I love how in programming, half the comments that help you are from over half a decade ago... xD

**Comment by QianKaiLu** [comment]
600 worked! Can someone tell me why 777 doesn't work?

**Comment by cmtatro** [comment]
I am sure you have figured this out, but as stated above:
https://github.com/ddollar/heroku-accounts/issues/15#issuecomment-32466275

Higher permissions causes some programs to exit out as it makes it insecure.

**Comment by susampath** [comment]
Thanks chmod 600 ~/.ssh/config works

**Comment by iamhaho** [comment]
This is magic that still works after 8 years...

**Comment by sunnykgupta** [comment]
600 did not work for me, but 6000 did. Thanks @vikasjiitk !

**Comment by potaty** [comment]
> 600 did not work for me, but 6000 did. Thanks @vikasjiitk !

Thank you! 6000 also works for me.

**Comment by agajdosi** [comment]
Thaaaanks!

**Comment by webslang** [comment]
Thanks!!!!

**Comment by LarsFinley** [comment]
sudo chmod 600 ~/.ssh/* worked for me

**Comment by antoniot87** [comment]
it's work for me thank's

**Comment by lopjf** [comment]
After few hours of struggling you provide exactly what I needed, thank you!

**Comment by KaynaL-MT** [comment]
wonderful, thank you for the solution @guapolo ; it also worked for me as well :)
