### ISSUE TITLE
'fatal: Not a git repository (or any of the parent directories): .git' at top of every Heroku shell response 

### ISSUE THREAD

**Issue by mmccroskey** [ddollar/heroku-accounts#39]
After installing heroku-accounts, every time I call the toolbelt from the command line, its response begins with `fatal: Not a git repository (or any of the parent directories): .git`. Uninstalling the toolbelt fixes the issue.

My version is `heroku-toolbelt/2.30.3 (universal-darwin11.0) ruby/1.8.7`.

**Comment by sailikhithk** [comment]
After creating app using heroku create app name, here is the problem. When I type "git add .", then this error is appearing, I can't proceed further.
Please help me fix this.
Thanks,
Sai Likhith
