### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by cspeer** [ddollar/heroku-accounts#47]
Hey,

I am using the latest heroku accounts with heroku-toolbelt/2.31.4. From one day to another, without me changing anything on the system, running any heroku command e.g. heroku run console, would tell me that the authentication failed and prompt me for user/pass.
First I thought this was an heroku related issue. But as I now found out, everyhting worked fine again as I removed the accounts plugin.

Nothing special about the output, I guess:
$ heroku run console
Running `console` attached to terminal... Authentication failure
Enter your Heroku credentials.

Cheers
Christopher

**Comment by jc00ke** [comment]
I just ran into it. email/password/2fa... auth failed :frowning: 

My internet connection at the coffee shop happened to drop when I was removing my acct (was going to try remove/add) and now everything I do I get `No such account: jc00ke`.

Even `heroku help` yields that `No such account: jc00ke` error.
