### ISSUE TITLE
Asks for passphrase when passphrase not required.

### ISSUE THREAD

**Issue by maxxiimo** [ddollar/heroku-accounts#60]
I've checked and rechecked my keys, some with passphrases, and others without. I generate my keys using git bash:

ssh-keygen -t rsa -C "sample@e-mail.com "

What I've found is that not using heroku-accounts, Heroku will accept the keys I create; all of them, with or without passphrases, and on different Heroku accounts I manage. 

For some reason, when I use heroku-accounts I keep running into the same issue which stops me from being able to use it: the keys that do not require a passphrase ask for one, and for the keys that do require a passphrase, the correct passphrase I enter is not accepted?

In .ssh\config:

ForwardAgent yes

Host heroku.personal
  HostName heroku.com
  IdentityFile "C:/Users/Chris/.ssh/id_rsa_max.pub"
  IdentitiesOnly yes

Host heroku.work
  HostName heroku.com
  IdentityFile "C:/Users/Chris/.ssh/id_rsa_ty.pub"
  IdentitiesOnly yes

FYI - through git bash on each test I double check my keys:

cd ~/.ssh
ssh-add -l
ssh-add -D
ssh-add ~/.ssh/id_rsa_ty

I also double check on Heroku:

heroku login
heroku keys:clear
heroku keys:add
<select key>
heroku keys (then check the Heroku control panel just in case)

...and double check here:

heroku accounts:set work
heroku accounts

In .git\config:

[core]
    repositoryformatversion = 0
    filemode = false
    bare = false
    logallrefupdates = true
    symlinks = false
    ignorecase = true
    hideDotFiles = dotGitOnly
[remote "heroku"]
    url = git@heroku.work:champion-fs.git
    fetch = +refs/heads/_:refs/remotes/heroku/_
[branch "master"]
    remote = heroku
    merge = refs/heads/master
[heroku]
    account = work

In my research I've looked at the following and tried numerous variations of what is suggested: 

Heroku:
[Managing Your SSH Keys](https://devcenter.heroku.com/articles/keys#adding_keys_to_heroku)
Github:
[Generating SSH Keys](https://help.github.com/articles/generating-ssh-keys)
[Working with SSH key passphrases](https://help.github.com/articles/working-with-ssh-key-passphrases)
[Error: Permission denied (publickey)](https://help.github.com/articles/error-permission-denied-publickey)
Stackoverflow:
[Cannot push to Heroku because key fingerprint](http://stackoverflow.com/questions/8786564/cannot-push-to-heroku-because-key-fingerprint)
[How to run (git/ssh) authentication agent?](http://stackoverflow.com/questions/4083079/how-to-run-git-ssh-authentication-agent)
[Switching between multiple ssh keys in Git on Windows](http://stackoverflow.com/questions/9672975/switching-between-multiple-ssh-keys-in-git-on-windows)

Not sure if this is a configuration issue on my part or possibly a real issue, but there it is.

One final thing, I'm on Windows 7. I know, why? I have to use Dragon NaturallySpeaking because of severe RSI and the version I need only works on Windows.

**Comment by Dulani** [comment]
> Anyone get a resolution to this issue. I'm currently experiencing a similar issue. I'm using no pass-phrase, and heroku is not liking that.

Just found a solution for myself.  My SSH key was missing the closing stanza: https://stackoverflow.com/questions/43724881/sshd-is-asking-for-a-passphrase-for-my-key-whereas-there-is-no-passphrase
