### ISSUE TITLE
WARNING: heroku-accounts plugin is installed. This plugin is known to have problems with HTTP Git.

### ISSUE THREAD

**Issue by enoughtoo** [ddollar/heroku-accounts#76]
I am using multiple heroku accounts on my PC with this awesome plugin. It was working perfectly. However, when I tried to check my apps of one account today, it started to update and then nothing works. I can still set heroku account for the folder however even at the previous configured folders, I run "heroku apps", it got:
````
    WARNING: heroku-accounts plugin is installed. This plugin is known to have problems with HTTP Git.
    Enter your Heroku credentials.
    Email:
````
and here no matter what account information I have entered, it will report "authorization fail".

**Comment by chanks** [comment]
I just spent a little while fighting this. Removing and readding the heroku account via the plugin worked for me, mostly. heroku accounts:add --auto messed up my SSH keys somehow, though, so be aware.

**Comment by Gazzini** [comment]
I'm having this issue as well; currently trying the delete/start over solution...

**Comment by gingermusketeer** [comment]
removing the account and adding it again worked for me

**Comment by gwagener** [comment]
This struck me after I added Heroku 2FA to an account. Not sure if that's related or not.

**Comment by honzajavorek** [comment]
Also got this error when I switched one of my accounts to 2FA.

**Comment by pmukerji** [comment]
Installing the fork from Heroku solved this issue for me: https://github.com/heroku/heroku-accounts

**Comment by jeromedoyle** [comment]
The solution offered by @pmukerji worked for me

**Comment by recurser** [comment]
I've also hit this after enabling 2FA.

> The solution offered by @pmukerji worked for me

likewise :+1:

**Comment by zakgrant** [comment]
same here :+1:

**Comment by derricklannaman** [comment]
Yup:+1:
