### ISSUE TITLE
heroku auth:token returns the same token for all accounts

### ISSUE THREAD

**Issue by honzajavorek** [ddollar/heroku-accounts#77]
Having `heroku-accounts` installed and using `personal` and `work` account, I did set the default account for particular apps. `heroku auth:whoami` returns different e-mails correctly, but `heroku auth:token` returns always the same token (probably of the first, default account). I had to perform `heroku logout` and `heroku login` with the other account so I could get my correct token.

This is very confusing and it took me some time to debug the problem.

**Comment by smcoll** [comment]
@ddollar is this closed as "fixed"?

**Comment by ddollar** [comment]
This is closed as "no longer maintained". Sorry! I don't think this plugin even works with the CLI any more.
