### ISSUE TITLE
Git doesn't seem to respect config

### ISSUE THREAD

**Issue by hhff** [ddollar/heroku-accounts#78]
I have everything setup how the readme explains, but it seems my git is not respecting my `~/.ssh/config` file, and attempting to `git push` with my regular `id_rsa` key.

Is there another step here?

**Comment by hhff** [comment]
scratch that, im good

**Comment by Domiii** [comment]
For me the two things that I missed at first:

1. Every line needs to be prefixed with (the same amount of?) whitespace
2. On Windows, command-line might have to be re-started after `config` has been changed
