### ISSUE TITLE
Multiple apps in folder and no app specified

### ISSUE THREAD

**Issue by jhubert** [ddollar/heroku-accounts#81]
Ever since setting up heroku:accounts, I am now unable to use remotes or default heroku apps. I have to specify the app for every call.

**Comment by edwardmp** [comment]
Same issue here.. would love it if I didn't have to specify --app each time

**Comment by jhubert** [comment]
fwiw, I solved this by using the official Heroku fork: https://github.com/heroku/heroku-accounts
