### ISSUE TITLE
Plugin is broken with multiple accounts

### ISSUE THREAD

**Issue by kurko** [ddollar/heroku-accounts#83]
```
→ heroku git:remote -a myapp
 ▸    You do not have access to the app myapp.
```

To fix that, just install the Heroku fork:

`heroku plugins:install https://github.com/heroku/heroku-accounts.git`

**Comment by rmm5t** [comment]
But the Heroku fork no longer supports configuring an account per project in the `.git/config` of the project. Total bummer.
