### ISSUE TITLE
WARNING: deprecated ddollar/heroku-accounts plugin is installed.

### ISSUE THREAD

**Issue by phoet** [ddollar/heroku-accounts#85]
i started getting this warning: `WARNING: deprecated ddollar/heroku-accounts plugin is installed.`

i checked if updating the plugin would remove it, but it didn't any pointers?

**Comment by bbonamin** [comment]
I'm having the same issue.

**Comment by glennfu** [comment]
+1

**Comment by dickeyxxx** [comment]
you can use this version: https://github.com/heroku/heroku-accounts

**Comment by phoet** [comment]
it looks like you need to reset the heroku remote url in order to use the official plugin

**Comment by bbonamin** [comment]
Yeah, you can either uninstall the plugin and install it from Heroku's, or do the following:
```bash
cd .heroku/plugins/heroku-accounts
git remote rm origin
git remote add origin https://github.com/heroku/heroku-accounts.git
git fetch
git merge origin/master
```

**Comment by istro** [comment]
Thanks!

**Comment by simeonwillbanks** [comment]
:+1: :100: @bbonamin Thanks!

**Comment by glennfu** [comment]
Thanks @bbonamin that was perfect

**Comment by jonathandean** [comment]
:trophy: appreciate the help @bbonamin :)

**Comment by kendagriff** [comment]
Thank you! @bbonamin

**Comment by johnlinvc** [comment]
Thanks! :100:

**Comment by imidsac** [comment]
Thank you! @bbonamin

**Comment by redaikidoka** [comment]
Heroku is now just uninstalling this plugin. Would you mark this project *deprecated*?
